### ISSUE TITLE
Modularize the Import Data interface from the Pandora skin

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/data-tools#1]
- [x] Modularize the Import Data interface from the Pandora skin.
- [x] Make this the interface for all data inputs across the different app. Ensure that any data checks made by the different app (e.g., checking if values are numeric) are kept in place.
  - Pandora-IsoMemo/bmsc-app#16
    - [x] main
    - [x] beta
  - Pandora-IsoMemo/bpred#19
    - [x] main
  - Pandora-IsoMemo/osteo-bior#15
    - [x] main
    - [x] beta
  - Pandora-IsoMemo/iso-app#91
    - [ ] main
    - [x] beta
  - Pandora-IsoMemo/plotr#22
    - [x] main
    - [x] beta
  - Pandora-IsoMemo/resources#70
    - [x] main
    - [x] beta

**Comment by arunge** [comment]
@isomemo The import module is available in all beta versions of the apps. The issue reported in https://github.com/Pandora-IsoMemo/bmsc-app/issues/18 was specific to the BMSC app. I added additional `tryCatch` statements to forward error messages to the user.

In the context of 
- https://github.com/Pandora-IsoMemo/data-tools/issues/28

I am currently collecting all places in the code that contain functions for modeling. While doing this, I am also checking if there are missing `tryCatch` statements.

Actually, you can already start testing the import module in other apps. Or, you wait until I have [checked all apps](https://github.com/Pandora-IsoMemo/data-tools/issues/28#issue-1587623554). Feel free to provide feedback at any time! :slightly_smiling_face:

**Comment by isomemo** [comment]
@arunge I will wait for your checks! An important note is that the import of the data via the module should preceed any of the implemented import checks.

**Comment by arunge** [comment]
All above was implemented. There was an update of the task regarding how data and models should be uploaded:
- https://github.com/Pandora-IsoMemo/data-tools/issues/50

Following issues are discussed in that ticket.
