### ISSUE TITLE
Integrate GPT-3 into Import Data module

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/data-tools#15]
**Idea:** Use GPT-3 to generate SQL queries for data preparations.

There is a _"community-maintained"_ R package for accessing the GPT-3 API: https://github.com/ben-aaron188/rgpt3.

- [x] Check requirements to access the API
  - for online version
  - for local installations of the app

**Comment by arunge** [comment]
To access the API one needs a key. For this, one needs to register for a free account:
- [ ] What are the limitations of a free account?
- [ ] How long is a key valid? See: Point 3. in https://github.com/ben-aaron188/rgpt3#known-issues-and-fixes

Applying the key:
- online version: we can set the key
- local version: 
  - the user will be asked for a key via a pop-up window
    - disadvantage: one has to enter the key each time one starts the app and wants to use GPT-3
  - alternative (but not planed to be implemented now):
    - place the key somewhere fixed
    - this would make the development and the installation of the docker container more complex
    - paths will vary between systems, one must catch all cases, e.g. check if the file with the key was found and is valid, advice where to put the file with the key, ...
    - effort only makes sense if many users need this feature and use apps locally

**Comment by arunge** [comment]
Regarding
> - [ ] What are the limitations of a free account?

The above R package uses https://openai.com/api/. Here we have different pricing for different models: https://openai.com/api/pricing/
Free usage is limited:
> Start for free
> Start experimenting with $18 in free credit that can be used during your first 3 months.

@isomemo Will we have budget for paying for a particular model?

A description of available models is here: https://platform.openai.com/docs/models/finding-the-right-model
There are special models to generate code: https://platform.openai.com/docs/models/codex

There is also **ChatGPT** which is currently free: https://chat.openai.com/auth/login and can be used via a chat interface. However, this seems to be busy from time to time:
   ![image](https://user-images.githubusercontent.com/16759098/216367340-e80349be-3273-40ba-9450-ea8e20a5c1e9.png)

@isomemo We should discuss the options here.

**Comment by isomemo** [comment]
@arunge when it comes to prices this is not a problem. Users will have to give their API key. I will work on the code for this.

**Comment by arunge** [comment]
The plan is now:
- to always ask for the access key file from the user within the UI
- use gpt3 to create an sql
- the sql query generated by gpt3 will be editable before its execution
- if the sql query is not valid there will be an error message exactly as there is one currently, e.g.
  ![image](https://user-images.githubusercontent.com/16759098/219413109-95c7974b-57ba-40d4-8052-2d08b4e1f1ea.png)

I created the respective UI and will develop the logic next.

**Comment by arunge** [comment]
The feature to use GPT3 was added to the dataTools package with [version 23.02.8](https://github.com/Pandora-IsoMemo/data-tools/pull/29). 

I will update the apps step by step and then it will be available also for the apps.
@isomemo I will notify you for which app you can start testing the gpt3 feature.

**Comment by isomemo** [comment]
@arunge could you please make this available today for IsoMemo app beta? I have a meeting this afternoon to discuss AI applications to our software and would like to show this feature.

**Comment by arunge** [comment]
I am already working on this. However, automatic tests must pass and package builds must succeed, sometimes this can take 30-60 minutes...

**Comment by arunge** [comment]
@isomemo The gpt3 package is not available on the server yet. I am working together with @jan-abel-inwt on that.
However, with a fresh installation (after pulling most recent updates) of the iso-app locally, the feature to use gpt3 should be available locally.

**Comment by arunge** [comment]
@isomemo There is an issue with the R version. The rgpt3 package requires a higher R version than we are using in our docker containers. We would have to upgrade the R version in order to make this feature available online.
Actually, I am developing on R version 4.2.2 for some time now, the chances are good that the apps will run after the upgrade. But of course I am not testing each single feature. In the worst case, the upgrade fails and the apps will still run on the previous R version.

Should we try an upgrade? But I have no idea how long this will take and if we have a chance to finish until this afternoon. On the other side we must upgrade anyway to make the gpt3 feature available.

However, currently(!), in order to make the newest version run locally you must(!) use an installation via R. The docker container only uses R version 4.1.2.

**Comment by isomemo** [comment]
@arunge Please go ahead with the upgrade!

**Comment by arunge** [comment]
Update: The first try to install all packages under R version 4.2.2 lead to an error. We must remove (for now) a deprecated package that is required for leaflet map export (the fancy map of the iso app; we will look for a solution later). We restarted the installation process.

**Comment by jan-abel-inwt** [comment]
The gpt-3 query feature should be available now in the [iso-memo-app-beta](https://pandoraapp.earth/app/iso-memo-app-beta)

**Comment by arunge** [comment]
@isomemo In order to make the new version of the iso-app beta running, we had to remove a package that is required for the export of the leaflet maps. We are looking for an alternative package to make the export work again. The gpt3 feature is not yet available for the other apps, since we must add the rgpt3 package (because it is not yet on CRAN) to every app manually. We will do so latest next week.

**Comment by isomemo** [comment]
@arunge thanks for letting me know! Please acknowledge when a fix is added.

**Comment by arunge** [comment]
We decided to add a note regarding uploading the key before usage of gpt3 will be possible.

To do:
- [ ] add a note, hide functionality of gpt3 until user confirmed the upload

**Comment by isomemo** [comment]
@arunge sounds good but the user should be able to easily activate gpt3.

**Comment by arunge** [comment]
@isomemo We gpt3 is now enabled for:
- https://isomemoapp.com/app/iso-memo-app-beta
- https://isomemoapp.com/app/resources-beta
- https://isomemoapp.com/app/plotr-beta

Could you please test the feature and let me know if the checkbox to confirm using gpt3 is fine for you?

**Comment by arunge** [comment]
@isomemo GPT3 is online for a while and was implemented as discussed so far. Please open a new ticket if you observe issues. All updates regarding the functionality will also be documented in a new ticket.
