### ISSUE TITLE
[MPI_WP2]: 3. Pandora skin & CRAN package

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/data-tools#18]
The Pandora skin from the IsoMemo app (https://github.com/Pandora-IsoMemo/iso-app) fetches data from the Pandora data platform (https://pandora.earth/). The platform is based on the CKAN open source data management system (https://ckan.org/). It is necessary to be familiar with CKAN terminology to interpret the instructions below.

- [x] Pandora-IsoMemo/data-tools#20

- [x] Pandora-IsoMemo/data-tools#19

- [x] Text filters by metadata. Each Pandora dataset folder includes metadata (see example: https://pandoradata.earth/dataset/archipelago-human-stable-isotope-database) and it should be possible to search by these fields. Text fields search by string and filters for numeric fields.
*CKAN - example:

![Image](https://user-images.githubusercontent.com/73887426/183864831-145edb88-f157-4e37-abfc-54121434959d.png)

- [x] #62

- [x] Order datasets and resources alphabetically

- [x] Tick boxes to select which resources to be made visible in the list “Pandora dataset resource” (xls, xlsx, csv, odt, txt, all)

For the GUI option to set location of North Arrow/Scale by coordinate and to set their size -> see: 
- https://github.com/Pandora-IsoMemo/iso-app/issues/69

---

- [x] #22
  - Function 1: 
    - To list available networks (groups in CKAN terminology, include string filtering)
    - To list available datasets (all or those within a specific network, include string filtering)
    - To list available resources within a dataset (all or filtered by file type as above, include also string filtering)
  - Function 2: 
    - to load data from a selected resource (as input user has to give dataset and resource names)
  - IMPORTANT: check if the CKAN API provides any kind of index value for groups/datasets/resources. If so, it should be possible to use these instead of the names since sometimes these can be quite long.

**Comment by arunge** [comment]
@isomemo Should the "Additional info" content be the content of the "About" (1) text?

![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/8d866779-bae3-4ce0-b123-057c3d7ce3bc)

**Comment by arunge** [comment]
@isomemo 
You can test following new features regarding the _Import Data_ module on [iso-app beta](https://isomemoapp.com/app/iso-memo-app-beta) with version 23.5.4.3:
- ordered datasets and resources (alphabetically)
- datasets can be filtered by strings in the meta information
- datasets can be filtered by CKAN Group
- pick the type to be shown under _Pandora dataset resource_

Still open from above:
- [ ] _About_ text
- [ ] Pandora CRAN package

**Comment by isomemo** [comment]
@arunge 

how does "Filter Pandora datasets" work? I entered some strings assuming that it would filter "datasets" but nothing happened.

Please rename:

"No Pandora group" to "No Pandora network"
"Filter Pandora datasets" to "Filter Pandora repositories"
"Pandora dataset" to "Pandora repository"
"Pandora dataset resource" to "Pandora repository resource"

**Comment by arunge** [comment]
@isomemo if you enter a string, all meta information will be checked for that string and only datasets that contain that string are selectable under "Pandora dataset", e.g. 

![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/5536def3-19a6-49b3-a75e-bdfb9a4d01ee)

Most likely the string "datasets" occurs the meta information of several Pandora datasets.

- [ ] I will rename labels as desired

**Comment by isomemo** [comment]
@arunge thanks! Is it possible to include a combination of keywords?

**Comment by arunge** [comment]
I am using the function `grepl` to identify strings, so yes by using `|` keywords can be combined:

![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/256c27e3-26c6-498b-b9ba-6c09fe04cb1e)

Maybe we can add an info icon (containing the description how to combine keywords) like in here?

![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/b16ec997-78c1-4ad3-8d6b-64906605f0c3)

**Comment by arunge** [comment]
@isomemo We have finished all left tasks here: "About" text and [CRAN package](https://cran.r-project.org/web/packages/Pandora/index.html).
