### ISSUE TITLE
Develop a Pandora CRAN package

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/data-tools#22]
Develop a Pandora CRAN package (called `pandora-data` analog to [isomemo-data](https://github.com/Pandora-IsoMemo/isomemo-data)) with similar options as available via the GUI having two main functions:
- [ ] Function 1: 
    - To list available networks (groups in CKAN terminology, include string filtering)
    - To list available datasets (all or those within a specific network, include string filtering)
    - To list available resources within a dataset (all or filtered by file type as above, include also string filtering)
- [ ] Function 2: 
    - to load data from a selected resource (as input user has to give dataset and resource names)
  
IMPORTANT: check if the CKAN API provides any kind of index value for groups/datasets/resources. If so, it should be possible to use these instead of the names since sometimes these can be quite long.

**Comment by arunge** [comment]
This issue should wait for finishing https://github.com/Pandora-IsoMemo/data-tools/issues/20

**Comment by arunge** [comment]
One note regarding the functions to be made available via CRAN:
In essence, the user should be able to use the same features as in the apps. So the features should be mimicked:

![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/9c070c91-024b-47b4-a692-fa95dbf16cd5)

- filter for meta data for strings (1)
- filter for the network (2)
- filter for the repository (3)
- filter for the file type (4)

**Comment by jan-abel-inwt** [comment]
Closed because issue moved to the new repository
