### ISSUE TITLE
URGENT: Pandora data import module stopped working!

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/data-tools#47]
@arunge see video: https://youtu.be/5D28pELh4LE

- [x] 1) Data import no longer working (see video). Must be related to recent changes.
- [x] 2) Missing renaming
- [x] 3) On the top left rename "importdata" to "Data import"
- [ ] 4) Also, please make the data preview optional using a checkbox. By default preview is not shown (I had also made this comment on another  -> #48

**Comment by arunge** [comment]
@isomemo I pushed a fix to dataTools that solves the [first three points](https://github.com/Pandora-IsoMemo/data-tools/issues/47#issue-1741925761). The fix is online for
- [x] iso-app beta
- [ ] bmsc app
- [ ] resources
- [ ] bpred
- [ ] plotr
- [ ] osteobior

Please let us discuss point 4.

**Comment by arunge** [comment]
@isomemo I have updated the import module in all apps. The fix is available on all online versions. I am closing here.
