### ISSUE TITLE
Modifications to data import module

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/data-tools#50]
@arunge 

The data import module can be used to import both data and models

There should be input parameters in the module that define its behaviour. Each app (or section within an app) will give values for these parameters. The goal is that the module adapts its behaviour in function of the app without having to change its core code.

Parameter 1: if the import is of data or models. If of models, then the tabs "Prepare", Merge", "Query with SQL" are disconnected
Parameter 2: if parameter 1 takes the value of "models" then parameter 2 sets the type of extension. In the module "File type" will only show this extension and the options "Sheet" and "First column contains rownames" will be deactivated.

The exported models will have extensions in function of the used app. They remain zip files but the extension will change. As for the selection strings use the app name whenever short enough and if you have doubts on the naming please ask.

For instance:

ReSources extension: .resources
Bpred extension: .bpred
BMSC extension: .bmsc

## To Do:
Apply module in the apps beta versions:
- [x] [ReSources](https://github.com/Pandora-IsoMemo/resources/pull/106) (.resources)
- [x] [Bpred](https://github.com/Pandora-IsoMemo/bpred/pull/34) (.bpred)
- [x] [BMSC-S](https://github.com/Pandora-IsoMemo/bmsc-app/pull/27) (.bmsc)
- [x] [PlotR](https://github.com/Pandora-IsoMemo/plotr/pull/43) (.plotr)
- [x] [DSSM](https://github.com/Pandora-IsoMemo/iso-app/pull/184) (.dssm)
- [x] [OsteoBioR](https://github.com/Pandora-IsoMemo/osteo-bior/pull/33) (.osteobior)

AND in a separate ticket:
- #56

**Comment by arunge** [comment]
@isomemo I updated the import data module (1) such that now models can be loaded. For testing purpose, this new version was integrated into [ReSources beta](https://isomemoapp.com/app/resources-beta). That is, now models can be loaded also from Pandora or url. 
![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/07ad00f5-020b-46ff-b549-6345a1a06e7b)

Additionally, the option to load online models can be found inside the import module (2)
 
![image](https://github.com/Pandora-IsoMemo/data-tools/assets/16759098/b03ef6ce-1ef6-45ff-92a2-6ad4fdcd0edf)

Please feel free to test this and let me know if something should be changed.

- [ ] the new file extensions are not yet implemented, e.g.
  > ReSources extension: .resources

**Comment by arunge** [comment]
Now, one is able to load model objects from pandora in all app's beta versions. I am closing here.
