### ISSUE TITLE
 Bug: Broken Functionality in Apps - SQL Query Generation with ChatGPT-3

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/data-tools#70]
## Current State

The functionality for SQL-query generation in our R Shiny app is currently broken. 

In https://github.com/Pandora-IsoMemo/data-tools/issues/15 sql-query generation was implemented via the [rgpt3](https://github.com/ben-aaron188/rgpt3) package. 

The functions of the rgpt3 package are not working properly anymore, leading to issues in our application (valid open-ai key are not accepted anymore).

## Proposal

I suggest we switch to using the [openai package](https://github.com/irudnyts/openai/), which appears to be better maintained and is already available on CRAN. This switch should help us reintegrate the SQL-query generation feature seamlessly into our apps.

* *CRAN Availability:* The fact that openai is on CRAN indicates a higher level of stability and reliability.
* *Active Development:* The openai package seems to be better maintained compared to rgpt3.

### Steps

1. Check if the functions of the openai package are similar to the ones that we are using right now.
2. Update the code to use the openai package for SQL-query generation. 

## Feedback Requested

@isomemo, what are your thoughts on this proposal? Do you agree with the decision to switch to the openai package?

**Comment by arunge** [comment]
There was a new release of the package rgpt: https://github.com/ben-aaron188/rgpt3/releases

- [ ] need to check if this fixed our issue

**Comment by jan-abel-inwt** [comment]
Changes in rgpt3 that are relevant for us:

- The naming of the function changed from `gpt3_...` to `rgpt_...`
- Only minor changes in the `_authenticate`, `_endsession` & `_apikey_form`
- `gpt3_single_completion()` does not exist anymore, because it was re-designed to accommodate and reflect changes in OpenAI's completion structure. Previously, there was a difference between text completions and chat completions. This is no longer the case. We now have to use the `rgpt_single()` function

**Comment by arunge** [comment]
@jan-abel-inwt What was the status here?

**Comment by jan-abel-inwt** [comment]
## Summary

* updated the naming of the `rgpt` function
* small changes in `rgpt_authenticate`, `rgpt_endsession` & `check_apikey_form`
* `rgpt_single()`replaces `gpt3_single_completion()`
   * default model `gpt-4-0125-preview`
   * set logprobs = FALSE
   * fixed the output of the function to be always be named list
* adjust ui functions in `02-importData-queryData.R` to be in line with the new changes
   * removed the parameter `n` to be adjusted by the user

**Comment by jan-abel-inwt** [comment]
see https://github.com/Pandora-IsoMemo/data-tools/issues/76#issuecomment-2044569609
