### ISSUE TITLE
Consider using openai python library for gpt functions

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/data-tools#76]
Although the functions of the `rgpt3` package are currently functional, it's essential to acknowledge potential future instability. We should consider alternative solutions, such as transitioning to the `openai` Python library using the `reticulate` package or exploring better-maintained R packages available on CRAN (currently there is none).

**Comment by isomemo** [comment]
@jan-abel-inwt @arunge this is connected to my previous comment on a separate thread concerning the rgpt failure. There I asked if we should indeed consider using the openai package although rgpt is now working. However, I did not realize that the openai package was built in Python which will require reticulate. Please advise if you think that this is a good solution for the future.

**Comment by arunge** [comment]
As just discussed and for purpose of documentation:
The [third option](https://github.com/Pandora-IsoMemo/data-tools/issues/76#issuecomment-2044569609) to integrate  the python library should remain _a third option_. It would increase dependencies and the complexity for our deployment if we had to integrate python code with `reticulate` into our shiny apps.
Ideally, we could use an up-to-date R package published on CRAN to reach the OpenAI API, which we currently do not have. We keep our eyes open ... :eyes: 

@jan-abel-inwt I am closing here.
