### ISSUE TITLE
Possible update: option to select the gpt model

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/data-tools#78]
> - Should the user choose the model?

For now, the feature is working as before. All additional options need to be discussed. I will open an issue for this.

...
_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/data-tools/issues/74#issuecomment-2035011279_

**Comment by arunge** [comment]
@isomemo We could integrate a new selection input to let the user choose a gpt model, which would be one of:
```
models = c('gpt-3.5-turbo-0125'
             , 'gpt-3.5-turbo'
             , 'gpt-3.5-turbo-1106'
             , 'gpt-3.5-turbo-16k'
             , 'gpt-3.5-turbo-0613'
             , 'gpt-3.5-turbo-16k-0613'
             , 'gpt-4'
             , 'gpt-4-0613'
             , 'gpt-4-0125-preview')
```

Would this be helpful for users? Or should we rely on one single model. And if so, do you have any preference? Currently we are using the default model `'gpt-3.5-turbo-1106'`.

**Comment by jan-abel-inwt** [comment]
We switched to the latest model `gpt-4-0125-preview` for now.

**Comment by isomemo** [comment]
@jan-abel-inwt thanks! Later we can discuss a possible switch to the openai package

**Comment by isomemo** [comment]
@jan-abel-inwt can we close this issue?

**Comment by arunge** [comment]
@isomemo There is only the question left if we should add a user input to let the user select the model. Currently we are just using the latest (`gpt-4-0125-preview`), which likely is the best option. Possibly, we should just leave it as it is. What do you think?

**Comment by isomemo** [comment]
@arunge the ideal would be to have the user select the model (also considering that new models will appear in the future)! If so, would this imply having different coding options in function of user model selection? If not, best to give the options otherwise leave it as is.

**Comment by arunge** [comment]
With [DataTools version 24.09.1](https://github.com/Pandora-IsoMemo/data-tools/pull/100) we do have the option to select the gpt model. 
With next feature updates of the apps this feature will also be available there. I am closing here.

![image](https://github.com/user-attachments/assets/6f53ef03-dc5e-488b-aa2d-6336a8648574)
