### ISSUE TITLE
Pandora compatibility for other apps

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/data-tools#86]
@isomemo We want to modify/adjust 7 exiting R apps so that they include the Pandora data import module (feeding data into the data), Save/Load model option, Docker installation, and online run.

Please, let me know which apps exactly should be modified by listing the links to the respective repositories!

**Comment by arunge** [comment]
@isomemo Today we discussed which apps are relevant here:

- **[CausalR](https://github.com/Pandora-IsoMemo/CausalR)**
  - [ ] Pandora data import module
  - [ ] Save/Load model option
  - [ ] Docker installation
  - [ ] online run
  - [ ] link to online version on https://isomemoapp.com/
- **[TraceR](https://github.com/Pandora-IsoMemo/TraceR)**
  - [ ] Pandora data import module
  - [ ] Save/Load model option
  - [x] Docker installation
  - [x] online run -> https://pandoraapp.earth/app/tracer-beta
  - [ ] link to online version on https://isomemoapp.com/
- **[MapR](https://github.com/Pandora-IsoMemo/MapR)**
  - [x] Pandora data import module
  - [ ] Save/Load model option
  - [x] Docker installation
  - [x] online run -> https://pandoraapp.earth/app/mapr-beta or https://pandoraapp.earth/app/mapr
  - [ ] link to online version on https://isomemoapp.com/
- **[BNR](https://github.com/Pandora-IsoMemo/BNR)**
  - [ ] Pandora data import module
  - [ ] Save/Load model option
  - [ ] Docker installation
  - [ ] online run
  - [ ] link to online version on https://isomemoapp.com/
- **[cycleR](https://github.com/Pandora-IsoMemo/cycleR)**
  - [ ] Pandora data import module
  - [ ] Save/Load model option
  - [ ] Docker installation
  - [ ] online run
  - [ ] link to online version on https://isomemoapp.com/

As discussed we will
- check which effort is needed to get apps online that are not an R package
- prioritize CausualR

**Comment by jan-abel-inwt** [comment]
TraceR & MapR are linked on the landing page https://isomemoapp.com/

@isomemo let me know if you want to change the text or the youtube links or something else

**Comment by arunge** [comment]
@jan-abel-inwt Regarding CausalR: I created a new branch `beta` in [CausalR](https://github.com/Pandora-IsoMemo/CausalR) containing 
- a clean R package structure to run a shiny app
- the scripts that are needed to run CausalR
- a Dockerfile

Could you please check the [beta branch](https://github.com/Pandora-IsoMemo/CausalR/tree/beta) and let me know if something is missing or if we can try to get the app running on shinyproxy?

**Comment by jan-abel-inwt** [comment]
The version of the beta branch can be found here https://isomemoapp.com/app/causalr-beta

**Comment by arunge** [comment]
@jan-abel-inwt I opened a [PR for Jian](https://github.com/Pandora-IsoMemo/CausalR/pull/26) where he can check the refactoring of his shiny app into a package. If he finishes testing and approves, we can merge and setup an online version for the main branch and after that link CausalR to the [landing page](https://isomemoapp.com/).

**Comment by arunge** [comment]
I opened an [issue](https://github.com/Pandora-IsoMemo/BNR/issues/2) regarding the online version of [BNR](https://github.com/Pandora-IsoMemo/BNR) and asked the developer if BNR is ready for the landing page https://isomemoapp.com/.
