### ISSUE TITLE
Adjust BMSCS Package Name in config.yaml

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/data-tools#88]
Adjust `BMSC-S` to `BMSCS` in https://github.com/Pandora-IsoMemo/data-tools/blob/9a4aa98e2e88b2b3d8b3ba674e91e8f8dac21eda/inst/config.yaml#L29

see: https://github.com/Pandora-IsoMemo/drat/issues/29#issuecomment-2141852772

**Comment by arunge** [comment]
This was solved with https://github.com/Pandora-IsoMemo/data-tools/commit/09cc6304b5e5f5ee4f7e374cbd9a426d97973aba
@jan-abel-inwt I am closing here.
